version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - botnet  # Connecting the bot service to a custom network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - botnet  # Connecting the redis service to the same custom network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local

networks:
  botnet:
    driver: bridge  # Defining a custom bridge network
